import InviteImg from "../assets/images/invite-img.png";
import Daniel from "../assets/images/daniel-img.png";
import Cody from "../assets/images/cody-img.png";
import StockMarketArrow from "../assets/images/stock-market-arrow.png";
import CarouselImg from "../assets/images/carousel-img.png";
import mainRoadImg from "../assets/images/main-road.png";
import mallStoreFront from "../assets/images/mall-storefront.png";
import mallPlaza from "../assets/images/mall-plaza.png";
import largeMallEstate from "../assets/images/large-mall-estate.png";
import sideShop from "../assets/images/side-shop.png";
import mallStoreFrontOne from "../assets/images/mall-storefront-one.png";
import mallPlazaOne from "../assets/images/mall-plaza-one.png";
import largeMallEstateOne from "../assets/images/large-mall-state-one.png";

const navbarTabs = [
  { tabId: 31, name: "Home", link: "" },
  { tabId: 32, name: "Dashboard", link: "dashboard" },
  { tabId: 33, name: "Leaderboards", link: "leaderboards" },
  { tabId: 34, name: "Community", link: "community" },
  { tabId: 35, name: "Tools", link: "tools" },
  { tabId: 36, name: "Browse", link: "browse" },
];

const leaderboardsTableData = [
  {
    title: "Virtual Land & Real Estate/NFTS (BsMetaverse/Web3/Gaming)",
    bgColor: "#8ff129",
    color: "black",
    data: [
      {
        id: 1,
        icon: "BsMeta",
        iconName: "Arra",
        iconSubTitle: "+2.54%",
        marketCap: "446,517,68",
        floor: "243",
        "1D vol": 7266,
        "1D%": "-55.2%",
        "7D Vol": "972.9%",
        "7D%": "-52.61",
        owners: "7.1k",
      },
      {
        id: 2,
        icon: "BsMeta",
        iconName: "Arra",
        iconSubTitle: "+2.54%",
        marketCap: "446,517,68",
        floor: "243",
        "1D vol": 7266,
        "1D%": "-55.2%",
        "7D Vol": "972.9%",
        "7D%": "-52.61",
        owners: "7.1k",
      },
      {
        id: 3,
        icon: "BsMeta",
        iconName: "Arra",
        iconSubTitle: "+2.54%",
        marketCap: "446,517,68",
        floor: "243",
        "1D vol": 7266,
        "1D%": "-55.2%",
        "7D Vol": "972.9%",
        "7D%": "-52.61",
        owners: "7.1k",
      },
      {
        id: 4,
        icon: "BsMeta",
        iconName: "Arra",
        iconSubTitle: "+2.54%",
        marketCap: "446,517,68",
        floor: "243",
        "1D vol": 7266,
        "1D%": "-55.2%",
        "7D Vol": "972.9%",
        "7D%": "-52.61",
        owners: "7.1k",
      },
      {
        id: 5,
        icon: "BsMeta",
        iconName: "Arra",
        iconSubTitle: "+2.54%",
        marketCap: "446,517,68",
        floor: "243",
        "1D vol": 7266,
        "1D%": "-55.2%",
        "7D Vol": "972.9%",
        "7D%": "-52.61",
        owners: "7.1k",
      },
    ],
  },
  {
    title: "Crowdfunding Market",
    bgColor: "#8ff129",
    color: "black",
    data: [
      {
        id: 1,
        icon: "BsMeta",
        iconName: "Arra",
        iconSubTitle: "+2.54%",
        marketCap: "446,517,68",
        floor: "243",
        "1D vol": 7266,
        "1D%": "-55.2%",
        "7D Vol": "972.9%",
        "7D%": "-52.61",
        owners: "7.1k",
      },
      {
        id: 2,
        icon: "BsMeta",
        iconName: "Arra",
        iconSubTitle: "+2.54%",
        marketCap: "446,517,68",
        floor: "243",
        "1D vol": 7266,
        "1D%": "-55.2%",
        "7D Vol": "972.9%",
        "7D%": "-52.61",
        owners: "7.1k",
      },
      {
        id: 3,
        icon: "BsMeta",
        iconName: "Arra",
        iconSubTitle: "+2.54%",
        marketCap: "446,517,68",
        floor: "243",
        "1D vol": 7266,
        "1D%": "-55.2%",
        "7D Vol": "972.9%",
        "7D%": "-52.61",
        owners: "7.1k",
      },
      {
        id: 4,
        icon: "BsMeta",
        iconName: "Arra",
        iconSubTitle: "+2.54%",
        marketCap: "446,517,68",
        floor: "243",
        "1D vol": 7266,
        "1D%": "-55.2%",
        "7D Vol": "972.9%",
        "7D%": "-52.61",
        owners: "7.1k",
      },
    ],
  },
  {
    title: "Phyrtual-Hybrid Market",
    bgColor: "#8ff129",
    color: "black",
    data: [
      {
        id: 1,
        icon: "BsMeta",
        iconName: "Arra",
        iconSubTitle: "+2.54%",
        marketCap: "446,517,68",
        floor: "243",
        "1D vol": 7266,
        "1D%": "-55.2%",
        "7D Vol": "972.9%",
        "7D%": "-52.61",
        owners: "7.1k",
      },
      {
        id: 2,
        icon: "BsMeta",
        iconName: "Arra",
        iconSubTitle: "+2.54%",
        marketCap: "446,517,68",
        floor: "243",
        "1D vol": 7266,
        "1D%": "-55.2%",
        "7D Vol": "972.9%",
        "7D%": "-52.61",
        owners: "7.1k",
      },
      {
        id: 3,
        icon: "BsMeta",
        iconName: "Arra",
        iconSubTitle: "+2.54%",
        marketCap: "446,517,68",
        floor: "243",
        "1D vol": 7266,
        "1D%": "-55.2%",
        "7D Vol": "972.9%",
        "7D%": "-52.61",
        owners: "7.1k",
      },
      {
        id: 4,
        icon: "BsMeta",
        iconName: "Arra",
        iconSubTitle: "+2.54%",
        marketCap: "446,517,68",
        floor: "243",
        "1D vol": 7266,
        "1D%": "-55.2%",
        "7D Vol": "972.9%",
        "7D%": "-52.61",
        owners: "7.1k",
      },
    ],
  },
];

const dashboardYourAssets = [
  {
    num: "one",
    title: "1.25 BTC",
    subTitle: "$2,4506",
    description: "Physical Real Estate",
    subDes: "+0.34%",
  },
  {
    num: "two",
    title: "0.32 LTC",
    subTitle: "$2,4506",
    description: "Metaverse Lands",
    subDes: "+0.34%",
  },
  {
    num: "three",
    title: "1.25 ETH",
    subTitle: "$2,4506",
    description: "Digital Assets",
    subDes: "+0.34%",
  },
  {
    num: "four",
    title: "6.73 BTC",
    subTitle: "$5,121.17",
    description: "Other Assets",
    subDes: "+0.34%",
  },
];

const dashboardPerformanceTable = [
  {
    id: "one",
    icon: "SmartCrowd",
    iconName: "SmartCrowd",
    iconSubTitle: "SMARTCRWD",
    price: "$2.56",
    chanee: "+13.56%",
    marketCap: "$400.8M",
  },
  {
    id: "two",
    icon: "GetStake",
    iconName: "GetStake",
    iconSubTitle: "GSTKD",
    price: "$10.43",
    chanee: "+11.19%",
    marketCap: "$400.8M",
  },
  {
    id: "three",
    icon: "Aqarchain",
    iconName: "Aqarchain",
    iconSubTitle: "AQAR",
    price: "$8.93",
    chanee: "-6.94%",
    marketCap: "$400.8M",
  },
  {
    id: "four",
    icon: "BsMeta",
    iconName: "Meta",
    iconSubTitle: "META",
    price: "$2.56",
    chanee: "-2.45%",
    marketCap: "$400.8M",
  },
  {
    id: "five",
    icon: "VelChain",
    iconName: "VelChain",
    iconSubTitle: "VET",
    price: "$112.14",
    chanee: "+6.80%",
    marketCap: "$400.8M",
  },
  {
    id: "six",
    icon: "AAVE",
    iconName: "AaVe",
    iconSubTitle: "AAVE",
    price: "$32.18",
    chanee: "+3.76%",
    marketCap: "$400.8M",
  },
];

const dashboardInviteData = [
  {
    title: "Get $10 in free real estate",
    subTitle: "Give a friend the gift of free real estate",
    description:
      "Invite a friend to araa & you'll both receive in free real estate assets when they buy or sell their first $100 on",
    img: InviteImg,
    subDes: "Only certain users can accept your invitation",
    terms: "View Terms & Conditions",
  },
];

const communityStoriesData = [
  {
    id: 6,
    name: "Your Story",
    img: Daniel,
  },
  {
    id: 7,
    name: "Cody Fisher",
    img: Cody,
  },
  {
    id: 8,
    name: "Your Story",
    img: Daniel,
  },
  {
    id: 9,
    name: "Cody Fisher",
    img: Cody,
  },
  {
    id: 10,
    name: "Your Story",
    img: Daniel,
  },
  {
    id: 11,
    name: "Cody Fisher",
    img: Cody,
  },
  {
    id: 12,
    name: "Your Story",
    img: Daniel,
  },
  {
    id: 13,
    name: "Cody Fisher",
    img: Cody,
  },
  {
    id: 14,
    name: "Your Story",
    img: Daniel,
  },
  {
    id: 15,
    name: "Cody Fisher",
    img: Cody,
  },
];

const communityDanielAccordian = [
  {
    name: "Daniel Saliba",
    img: Daniel,
    carouselImg: CarouselImg,
    location: "Dubai UAE",
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat null pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
  },
];

const communityDanielInfo = [
  {
    name: "Daniel Saliba",
    img: Daniel,
    mail: "@danielsaliba",
    location: "Dubai UAE",
    posts: "2.6k",
    following: 1050,
    followers: 2400,
  },
];

const communityTrendingData = [
  {
    title: "Trending News",
    btn: "View All",
    img: StockMarketArrow,
    titleOne: "Crypto Big Losses...",
    titleTwo: "Bitcoin Make S&P No. 1",
    titleThree: "#Crypto",
    descOne: "Read More",
    descTwo: "Read More",
    descThree: "Ethereum",
  },
  {
    title: "Trending Groups",
    btn: "View All",
    img: StockMarketArrow,
    titleOne: "#AraaRealEstate",
    titleTwo: "#Games",
    titleThree: "#Crypto",
    descOne: "1040 Posts",
    descTwo: "547 Posts",
    descThree: "Ethereum",
  },
];

const browseData = [
  {
    tabName: "Virtual Land",
    tabId: "virtualLand",
    activeTab: " active",
    ariaSelected: true,
    showClass: " show",
    browseCardData: [
      {
        cardId: "card1",
        name: "Main Road",
        count: "5,777",
        subName: "Ethereum",
        subCount: "20,141",
        img: mainRoadImg,
      },
      {
        cardId: "card2",
        name: "Mall Storefront",
        count: "10,245",
        subName: "Ethereum",
        subCount: "-146,13",
        img: mallStoreFront,
      },
      {
        cardId: "card3",
        name: "Mall Plaza",
        count: "510,245",
        subName: "Ethereum",
        subCount: "50 LAND",
        img: mallPlaza,
      },
      {
        cardId: "card4",
        name: "Large Mall Estate",
        count: "810,123",
        subName: "Ethereum",
        subCount: "55 LAND",
        img: largeMallEstate,
      },
      {
        cardId: "card5",
        name: "Main Road",
        count: "5,777",
        subName: "Ethereum",
        subCount: "20,141",
        img: sideShop,
      },
      {
        cardId: "card6",
        name: "Mall Storefront",
        count: "10,245",
        subName: "Ethereum",
        subCount: "-146,13",
        img: mallStoreFrontOne,
      },
      {
        cardId: "card7",
        name: "Mall Plaza",
        count: "510,245",
        subName: "Ethereum",
        subCount: "50 LAND",
        img: mallPlazaOne,
      },
      {
        cardId: "card8",
        name: "Large Mall Estate",
        count: "810,123",
        subName: "Ethereum",
        subCount: "55 LAND",
        img: largeMallEstateOne,
      },
    ],
  },
  {
    tabName: "Crowdfunding",
    tabId: "crowdFunding",
    activeTab: "",
    ariaSelected: false,
    showClass: "",
    browseCardData: [
      {
        cardId: "card9",
        name: "Main Road",
        count: "5,777",
        subName: "Ethereum",
        subCount: "20,141",
        img: mainRoadImg,
      },
      {
        cardId: "card10",
        name: "Mall Storefront",
        count: "10,245",
        subName: "Ethereum",
        subCount: "-146,13",
        img: mallStoreFront,
      },
      {
        cardId: "card11",
        name: "Mall Plaza",
        count: "510,245",
        subName: "Ethereum",
        subCount: "50 LAND",
        img: mallPlaza,
      },
      {
        cardId: "card12",
        name: "Large Mall Estate",
        count: "810,123",
        subName: "Ethereum",
        subCount: "55 LAND",
        img: largeMallEstate,
      },
      {
        cardId: "card13",
        name: "Main Road",
        count: "5,777",
        subName: "Ethereum",
        subCount: "20,141",
        img: sideShop,
      },
      {
        cardId: "card14",
        name: "Mall Storefront",
        count: "10,245",
        subName: "Ethereum",
        subCount: "-146,13",
        img: mallStoreFrontOne,
      },
      {
        cardId: "card15",
        name: "Mall Plaza",
        count: "510,245",
        subName: "Ethereum",
        subCount: "50 LAND",
        img: mallPlazaOne,
      },
      {
        cardId: "card16",
        name: "Large Mall Estate",
        count: "810,123",
        subName: "Ethereum",
        subCount: "55 LAND",
        img: largeMallEstateOne,
      },
    ],
  },
  {
    tabName: "NFTS",
    tabId: "nfts",
    activeTab: "",
    ariaSelected: false,
    showClass: "",
    browseCardData: [
      {
        cardId: "card17",
        name: "Main Road",
        count: "5,777",
        subName: "Ethereum",
        subCount: "20,141",
        img: mainRoadImg,
      },
      {
        cardId: "card18",
        name: "Mall Storefront",
        count: "10,245",
        subName: "Ethereum",
        subCount: "-146,13",
        img: mallStoreFront,
      },
      {
        cardId: "card19",
        name: "Mall Plaza",
        count: "510,245",
        subName: "Ethereum",
        subCount: "50 LAND",
        img: mallPlaza,
      },
      {
        cardId: "card20",
        name: "Large Mall Estate",
        count: "810,123",
        subName: "Ethereum",
        subCount: "55 LAND",
        img: largeMallEstate,
      },
      {
        cardId: "card21",
        name: "Main Road",
        count: "5,777",
        subName: "Ethereum",
        subCount: "20,141",
        img: sideShop,
      },
      {
        cardId: "card22",
        name: "Mall Storefront",
        count: "10,245",
        subName: "Ethereum",
        subCount: "-146,13",
        img: mallStoreFrontOne,
      },
      {
        cardId: "card23",
        name: "Mall Plaza",
        count: "510,245",
        subName: "Ethereum",
        subCount: "50 LAND",
        img: mallPlazaOne,
      },
      {
        cardId: "card24",
        name: "Large Mall Estate",
        count: "810,123",
        subName: "Ethereum",
        subCount: "55 LAND",
        img: largeMallEstateOne,
      },
    ],
  },
  {
    tabName: "Tokenization",
    tabId: "tokeniZation",
    activeTab: "",
    ariaSelected: false,
    showClass: "",
    browseCardData: [
      {
        cardId: "card25",
        name: "Main Road",
        count: "5,777",
        subName: "Ethereum",
        subCount: "20,141",
        img: mainRoadImg,
      },
      {
        cardId: "card26",
        name: "Mall Storefront",
        count: "10,245",
        subName: "Ethereum",
        subCount: "-146,13",
        img: mallStoreFront,
      },
      {
        cardId: "card27",
        name: "Mall Plaza",
        count: "510,245",
        subName: "Ethereum",
        subCount: "50 LAND",
        img: mallPlaza,
      },
      {
        cardId: "card28",
        name: "Large Mall Estate",
        count: "810,123",
        subName: "Ethereum",
        subCount: "55 LAND",
        img: largeMallEstate,
      },
      {
        cardId: "card29",
        name: "Main Road",
        count: "5,777",
        subName: "Ethereum",
        subCount: "20,141",
        img: sideShop,
      },
      {
        cardId: "card30",
        name: "Mall Storefront",
        count: "10,245",
        subName: "Ethereum",
        subCount: "-146,13",
        img: mallStoreFrontOne,
      },
      {
        cardId: "card31",
        name: "Mall Plaza",
        count: "510,245",
        subName: "Ethereum",
        subCount: "50 LAND",
        img: mallPlazaOne,
      },
      {
        cardId: "card32",
        name: "Large Mall Estate",
        count: "810,123",
        subName: "Ethereum",
        subCount: "55 LAND",
        img: largeMallEstateOne,
      },
    ],
  },
  {
    tabName: "Hybrid Link",
    tabId: "hybridLink",
    activeTab: "",
    ariaSelected: false,
    showClass: "",
    browseCardData: [
      {
        cardId: "card33",
        name: "Main Road",
        count: "5,777",
        subName: "Ethereum",
        subCount: "20,141",
        img: mainRoadImg,
      },
      {
        cardId: "card34",
        name: "Mall Storefront",
        count: "10,245",
        subName: "Ethereum",
        subCount: "-146,13",
        img: mallStoreFront,
      },
      {
        cardId: "card35",
        name: "Mall Plaza",
        count: "510,245",
        subName: "Ethereum",
        subCount: "50 LAND",
        img: mallPlaza,
      },
      {
        cardId: "card36",
        name: "Large Mall Estate",
        count: "810,123",
        subName: "Ethereum",
        subCount: "55 LAND",
        img: largeMallEstate,
      },
      {
        cardId: "card37",
        name: "Main Road",
        count: "5,777",
        subName: "Ethereum",
        subCount: "20,141",
        img: sideShop,
      },
      {
        cardId: "card38",
        name: "Mall Storefront",
        count: "10,245",
        subName: "Ethereum",
        subCount: "-146,13",
        img: mallStoreFrontOne,
      },
      {
        cardId: "card39",
        name: "Mall Plaza",
        count: "510,245",
        subName: "Ethereum",
        subCount: "50 LAND",
        img: mallPlazaOne,
      },
      {
        cardId: "card40",
        name: "Large Mall Estate",
        count: "810,123",
        subName: "Ethereum",
        subCount: "55 LAND",
        img: largeMallEstateOne,
      },
    ],
  },
  {
    tabName: "My Store",
    tabId: "myStore",
    activeTab: "",
    ariaSelected: false,
    showClass: "",
    browseCardData: [
      {
        cardId: "card41",
        name: "Main Road",
        count: "5,777",
        subName: "Ethereum",
        subCount: "20,141",
        img: mainRoadImg,
      },
      {
        cardId: "card42",
        name: "Mall Storefront",
        count: "10,245",
        subName: "Ethereum",
        subCount: "-146,13",
        img: mallStoreFront,
      },
      {
        cardId: "card43",
        name: "Mall Plaza",
        count: "510,245",
        subName: "Ethereum",
        subCount: "50 LAND",
        img: mallPlaza,
      },
      {
        cardId: "card44",
        name: "Large Mall Estate",
        count: "810,123",
        subName: "Ethereum",
        subCount: "55 LAND",
        img: largeMallEstate,
      },
      {
        cardId: "card45",
        name: "Main Road",
        count: "5,777",
        subName: "Ethereum",
        subCount: "20,141",
        img: sideShop,
      },
      {
        cardId: "card46",
        name: "Mall Storefront",
        count: "10,245",
        subName: "Ethereum",
        subCount: "-146,13",
        img: mallStoreFrontOne,
      },
      {
        cardId: "card47",
        name: "Mall Plaza",
        count: "510,245",
        subName: "Ethereum",
        subCount: "50 LAND",
        img: mallPlazaOne,
      },
      {
        cardId: "card48",
        name: "Large Mall Estate",
        count: "810,123",
        subName: "Ethereum",
        subCount: "55 LAND",
        img: largeMallEstateOne,
      },
    ],
  },
];

export {
  navbarTabs,
  leaderboardsTableData,
  dashboardYourAssets,
  dashboardPerformanceTable,
  dashboardInviteData,
  communityStoriesData,
  communityDanielInfo,
  communityTrendingData,
  communityDanielAccordian,
  browseData,
};
